version: '3.8'
services:
  web:
    container_name: my-web-php
    build:
      context: .
      dockerfile: Dockerfile
    volumes :
      - ./src:/var/www/html/
    ports:
      - "8000:80"
    depends_on:
      - database

  database:
    container_name: database
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: binotify
      MYSQL_USER: tubes1
      MYSQL_PASSWORD: rootpass

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - database
